### ISSUE TITLE
Add placeholder text to search input 

### ISSUE THREAD

**Issue by HarryTrimble** [govbins/govbins.uk#51]
@tommyp Add placeholder text to search input - 'Search catalogue' in #1f2937

**Comment by tommyp** [comment]
@HarryTrimble I've already set it to [autofocus](https://github.com/govbins/govbins.uk/issues/53) which means the user won't see the placeholder until they remove focus from the input.

**Comment by tommyp** [comment]
Solved by https://github.com/govbins/govbins.uk/pull/48/commits/25ff0c108b8ac8c74496762087917d37dc4c66b0
