### ISSUE TITLE
Auto add cursor to search input

### ISSUE THREAD

**Issue by HarryTrimble** [govbins/govbins.uk#53]
@tommyp Auto add the cursor to search input to speed up people search - as it does on Google search
<img width="1111" alt="Screenshot 2021-07-25 at 12 59 36" src="https://user-images.githubusercontent.com/12497586/126898248-bd8b2af2-81b6-40b6-8c77-cb4cb7c494cc.png">

**Comment by tommyp** [comment]
Solved by [https://github.com/govbins/govbins.uk/pull/48/commits/d59c4aea15645c782ef65a5015207313b462ce25](d59c4aea15645c782ef65a5015207313b462ce25)
